server:
  port: 58220

logging:
  level:
    com.datacent.agent: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  console:
    enabled: true
    # 确保日志立即输出到控制台，不缓存
    immediateFlush: true
  file:
    name: logs/mcp-tool-analysis.log
    # 同时输出到文件
    immediateFlush: true
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 5

spring:
  main:
    banner-mode: off
  application:
    name: chat-stream-proxy-service

# 聊天流式接口配置
chat:
  stream:
    base-url: http://192.168.3.78:48558





